/*
 * Stoatworks Labs - About window data for (re)gauss.
 *
 * NORMALLY GENERATED by stoatworks-backend/scripts/sync-about.py from the
 * website's projects.json, which is the one place these facts are written
 * down. This copy is hand-written because (re)gauss does not have a
 * projects.json entry yet: the website card and the user guide are part of the
 * release, and they do not exist while the plugin is still being built.
 *
 * `guide` and `page` are therefore deliberately EMPTY. StoatworksAboutParams.h
 * leaves a button out of the list when its URL is blank, which is the whole
 * point -- a "User guide" button that opens a 404 is worse than no button. Add
 * the projects.json entry and re-run the sync before release, and both buttons
 * appear on their own.
 *
 * `version` here is a fallback; the build injects the real one.
 */
#pragma once

namespace stoatworks::about
{
    inline constexpr auto name = "Vectrix";
    inline constexpr auto slug = "vectrix";
    inline constexpr auto hook = "A vector-CRT synth for Resolume: oscillator, pedals, oscilloscope";
    inline constexpr auto licence = "MIT";
    inline constexpr auto guide = "";
    inline constexpr auto page = "https://stoatworks-labs.com/software/vectrix/";
    inline constexpr auto repo = "https://github.com/stoatworks-labs/vectrix";
    inline constexpr auto versionFallback = "v0.1.0";

    inline constexpr auto org = "Stoatworks Labs";
    inline constexpr auto home = "https://stoatworks-labs.com";
    inline constexpr auto tagline = "Open tools for the people who run the show.";

    /* The canonical funding links, matching FUNDING.yml and the support footer. */
    struct Link { const char* name; const char* url; };
    inline constexpr Link funding[] = {
        { "GitHub Sponsors", "https://github.com/sponsors/stoatworks-labs" },
        { "Ko-fi", "https://ko-fi.com/stoatworkslabs" },
        { "Patreon", "https://patreon.com/StoatworksLabs" },
        { "Liberapay", "https://liberapay.com/stoatworks-labs" },
    };
}
